uk:
  gov:
    hmcts:
      dependency:
        fieldGroupDependency:
          FL401:
            - applyingWithoutGivingNotice:
              dependentFields:
                - orderWithoutGivingNoticeReason1
                - orderWithoutGivingNoticeReason2
                - orderWithoutGivingNoticeReason3
              dependentFieldValue: "*"
              groupFieldName: orderWithout_GivingNotice
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "1.3 - Why do you want to apply without giving notice to the respondent?"
            - bailCondition:
              dependentFields:
                - respondentBailConditions_EndDate_Day
                - respondentBailConditions_EndDate_Month
                - respondentBailConditions_EndDate_Year
              dependentFieldValue: "*"
              groupFieldName: respondentBailConditions
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "1.6 - When do the bail conditions end?"
            - goingToCourt:
              dependentFields:
                  - disabilitySupport_details
              dependentFieldValue: "*"
              groupFieldName: disabilitySupport_NeededAtCourt
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "8 - going To Court"
            - interpreterNeededAtCourt:
              dependentFields:
                - InterpreterNeededAtCourt_Language
                - InterpreterNeededAtCourt_Dialect
              dependentFieldValue: "*"
              groupFieldName: InterpreterNeededAtCourt
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "8 - going To Court"
            - contactDetails:
              dependentFields:
                - applicant_Address_BuildingAndStreet
                - applicant_Address_TownOrCity
                - applicant_Address_Postcode
                - applicant_PhoneNumber
                - applicant_Email
              dependentFieldValue: "*"
              groupFieldName: applicantContact_Confidentiality
              groupValidationValue: "Yes"
              requiredFieldCount: 5
              sectionName: "2 - Address, email and phone number are mandatory"
            - occupationOrderAddressGroup:
              dependentFields:
                - occupationOrderAddress_BuildingAndStreet
                - occupationOrderAddress_SecondLine
                - occupationOrderAddress_TownOrCity
                - occupationOrderAddress_Postcode
                - occupationOrderAddress_PreviousOccupant
              dependentFieldValue: "*"
              groupFieldName: ApplyingForOccupationOrder
              groupValidationValue: "Yes"
              requiredFieldCount: 2
              sectionName: "To what address do you want the occupation order to apply?"
            - occupationOrderCurrentOccupantGroup:
              dependentFields:
                - occupationOrderAddress_CurrentOccupant_applicant
                - occupationOrderAddress_CurrentOccupant_respondent
                - occupationOrderAddress_CurrentOccupant_children
                - occupationOrderAddress_CurrentOccupant_other
              dependentFieldValue: "*"
              groupFieldName: ApplyingForOccupationOrder
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "Who currently lives at the address?"
            - occupationOrderMandatoryHomeGroup:
              dependentFields:
                - MortgageOnProperty
                - RentedProperty
                - HomeRights
              dependentFieldValue: "*"
              groupFieldName: ApplyingForOccupationOrder
              groupValidationValue: "Yes"
              requiredFieldCount: 3
              sectionName: "MortgageOnProperty, RentedProperty, HomeRights, please provide Yes or No"
            - occupationOrderCurrentOccupantOtherGroup:
              dependentFields:
                - occupationOrderAddress_CurrentOccupant_others
              dependentFieldValue: "*"
              groupFieldName: occupationOrderAddress_CurrentOccupant_other
              groupValidationValue: "Others"
              requiredFieldCount: 1
              sectionName: "Occupation order - Current occupant -> Someone else – please specify."
            - occupationOrderIntendedOccupantGroup:
              dependentFields:
                - occupationOrderAddress_IntentedOccupant
              dependentFieldValue: "*"
              groupFieldName: occupationOrderAddress_PreviousOccupant
              groupValidationValue: "No"
              requiredFieldCount: 1
              sectionName: "If you answered ‘No’ to question 7.4, did you or the respondent ever intend to live at the address?"
            - propertySpeciallyAdaptedGroup:
              dependentFields:
                - propertySpeciallyAdapted_Details
              dependentFieldValue: "*"
              groupFieldName: propertySpeciallyAdapted
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "Please provide details of how the property is specially adapted."
            - mortgageOnPropertyGroup:
              dependentFields:
                - MortgageOnProperty_Person_applicant
                - MortgageOnProperty_Person_respondant
                - MortgageOnProperty_Person_other
                - MortgageOnProperty_Number
                - MortgageLender_Name
                - MortgageLender_BuildingAndStreet
                - MortgageLender_SecondLine
                - MortgageLender_TownOrCity
                - MortgageLender_Postcode
              dependentFieldValue: "*"
              groupFieldName: MortgageOnProperty
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "Is there a mortgage on the property?"
            - mortgageOnPropertySomeoneElseGroup:
              dependentFields:
                - MortgageOnProperty_Person_Others
              dependentFieldValue: "*"
              groupFieldName: MortgageOnProperty_Person_other
              groupValidationValue: "someoneElse"
              requiredFieldCount: 1
              sectionName: "Someone else – please specify"
            - propertyRentedGroup:
              dependentFields:
                - RentedProperty_Person
                - LandlordDetails_Name
                - LandlordDetails_BuildingAndStreet
                - LandlordDetails_SecondLine
                - LandlordDetails_TownOrCity
                - LandlordDetails_Postcode
              dependentFieldValue: "*"
              groupFieldName: RentedProperty
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "Who is named on the rental agreement? Please select all that apply"
            - propertyRentedSomeoneElseGroup:
              dependentFields:
                - RentedProperty_Person_Others
              dependentFieldValue: "*"
              groupFieldName: RentedProperty
              groupValidationValue: "Someone else – please specify"
              requiredFieldCount: 1
              sectionName: "Someone else – please specify"
            - yourFamilyGroup:
              dependentFields:
                - family_childrenDetails_row1
                - family_childrenDetails_row2
                - family_childrenDetails_row3
                - family_childrenDetails_row4
                - OngoingFamilyCourtProceeding
              dependentFieldValue: "*"
              groupFieldName: applicationFor_Yourfamily
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "5.3 - Details of the child or children to be protected by the order"
            - OngoingCourtProceedingGroup:
              dependentFields:
                - OngoingFamilyCourtProceeding_row1
                - OngoingFamilyCourtProceeding_row2
                - OngoingFamilyCourtProceeding_row3
              dependentFieldValue: "*"
              groupFieldName: OngoingFamilyCourtProceeding
              groupValidationValue: "Yes"
              requiredFieldCount: 1
              sectionName: "5.4 - Family court proceedings details"
            - OccupationOrderGroup:
              dependentFields:
                - ApplyingForOccupationOrder
              dependentFieldValue: "*"
              groupFieldName: orderApplyingFor_occupation
              groupValidationValue: "occupationOrder"
              requiredFieldCount: 1
              sectionName: "7.1 - Are you applying for an occupation order?"

